# Generated by Django 5.2.4 on 2025-07-16 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='mentor',
            field=models.ForeignKey(default=15, limit_choices_to={'groups__name': 'Mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentee_goals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
