# Generated by Django 5.2.4 on 2025-07-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_mentor_availability_mentor_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('PHONE_CALL', 'Phone Call'), ('VIDEO_CALL', 'Video Call'), ('CHAT', 'Chat'), ('IN_PERSON', 'In Person')], default='VIDEO_CALL', help_text='Type of mentorship session (e.g., Video Call, Phone Call)', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', help_text='Current status of the session', max_length=20)),
                ('location_details', models.CharField(blank=True, help_text='Details for the session location (e.g., Zoom link, phone number, address)', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_sessions', to='mentorship.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to='mentorship.mentor')),
                ('mentorship_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mentorship.mentorshiprequest')),
            ],
            options={
                'verbose_name': 'Mentorship Session',
                'verbose_name_plural': 'Mentorship Sessions',
                'ordering': ['start_time'],
            },
        ),
    ]
