# Generated by Django 5.2.4 on 2025-07-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiprequest',
            name='is_session_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
