# Generated by Django 5.2.4 on 2025-07-12 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_mentorshiprequest_is_session_scheduled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('mentorship_request', models.ForeignKey(blank=True, help_text='The mentorship request this message pertains to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentorship.mentorshiprequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Message',
                'verbose_name_plural': 'User Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
