# Generated by Django 5.2.4 on 2025-07-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='mentee',
        ),
        migrations.RemoveField(
            model_name='session',
            name='mentor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='availabile_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='available_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
