# Generated by Django 5.2.4 on 2025-07-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0006_remove_session_mentee_remove_session_mentor_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mentorshiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED'])), fields=('mentee', 'mentor'), name='unique_pending_or_accepted_request'),
        ),
    ]
