# Generated by Django 5.2.4 on 2025-07-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_mentorshiprequest_unique_pending_or_accepted_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
