# Generated by Django 5.2.4 on 2025-07-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_mentorshiprequest_unique_pending_or_accepted_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
