# Generated by Django 5.2.4 on 2025-07-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0008_mentee_contact_mentor_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('content_clarity', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('neutral', 'Neutral')], max_length=10)),
                ('relevance', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('neutral', 'Neutral')], max_length=10)),
                ('structure', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('neutral', 'Neutral')], max_length=10)),
                ('mentor_support', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('neutral', 'Neutral')], max_length=10)),
                ('mentor_listening', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('neutral', 'Neutral')], max_length=10)),
                ('mentor_knowledge', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('neutral', 'Neutral')], max_length=10)),
                ('mentor_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('learning', models.TextField()),
                ('expectations_met', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partially')], max_length=10)),
                ('expectations_explanation', models.TextField()),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='mentorship.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='mentorship.mentor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='mentorship.session')),
            ],
            options={
                'unique_together': {('session', 'mentee')},
            },
        ),
    ]
