# Generated by Django 5.2.4 on 2025-07-17 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('punctuality', models.CharField(choices=[('always_on_time', 'Always On Time'), ('sometimes_late', 'Sometimes Late'), ('frequently_absent', 'Frequently Absent')], max_length=20)),
                ('preparedness', models.CharField(choices=[('well_prepared', 'Well-prepared'), ('somewhat_prepared', 'Somewhat Prepared'), ('unprepared', 'Unprepared')], max_length=20)),
                ('participation', models.CharField(choices=[('highly_engaged', 'Highly Engaged'), ('engaged', 'Engaged'), ('somewhat_engaged', 'Somewhat Engaged'), ('not_participative', 'Not Participative')], max_length=20)),
                ('responsiveness', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=10)),
                ('initiative', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('initiative_comment', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_improvement', 'Needs Improvement')], max_length=20)),
                ('improvement_since_last', models.TextField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('tasks_completed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('tasks_comment', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('overall_evaluation', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_improvement', 'Needs Improvement')], max_length=20)),
                ('recommend_advanced', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('recommend_comment', models.TextField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_evaluations', to='mentorship.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_evaluations', to='mentorship.mentor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_evaluations', to='mentorship.session')),
            ],
            options={
                'unique_together': {('session', 'mentor', 'mentee')},
            },
        ),
    ]
