# Generated by Django 5.2.4 on 2025-07-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0008_session_topic'),
        ('mentorship', '0010_mentorevaluation'),
    ]

    operations = [
    ]
