# Generated by Django 5.2.4 on 2025-07-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0010_mentorevaluation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorshiprequest',
            unique_together=set(),
        ),
    ]
