# Generated by Django 5.2.4 on 2025-07-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0011_alter_mentorshiprequest_unique_together'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mentorshiprequest',
            name='unique_pending_or_accepted_request',
        ),
    ]
