# Generated by Django 5.2.4 on 2025-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
